// ==UserScript==
// @name           GE2024: Reform UK
// @namespace      sjorford@gmail.com
// @version        2024.01.12.0
// @author         Stuart Orford
// @match          https://www.reformparty.uk/find-my-candidate
// @match          https://en.wikipedia.org/w/index.php?title=Wikipedia:Sandbox*
// @grant          none
// ==/UserScript==

(function($) {
$(function() {
	
	$(`<style>
		.sjo-urls-box a {white-space: nowrap;}
	</style>`).appendTo('head');
	
	var box = $('<div class="sjo-urls-box"></div>').insertAfter('#intro');
	var constituencies = getConstituencies();
	$.each(constituencies, (i,e) => {
		if (i > 0) box.append(' • ');
		var url = `https://www.reformparty.uk/${e.slug}`;
		if (e.slug != 'east-grinstead-and-uckfield') url += '-constituency';
		var link = $('<a></a>').attr('href', url).text(e.name);
		link.appendTo(box);
	});
	
	/*
	$.ajaxPrefilter(function(options, originalOptions, jqXHR) {
		console.log('options', options);
		//delete options.headers['Cookie'];
	});
	
	var regionURLs = $('#intro a[href$="-region"]').toArray().map(e => e.href);
	console.log('regionURLs', regionURLs);
	
	var constituencyURLs = $('a[href$="-constituency"]').toArray().map(e => e.href);
	console.log('constituencyURLs', constituencyURLs);
	
	if (regionURLs.length > 0) {
		downloadRegion();
	} else if (constituencyURLs.length > 0) {
		downloadConstituency();
	}
	
	function downloadRegion() {
		if (regionURLs.length == 0) {
			downloadConstituency();
			return;
		}
		var url = regionURLs.shift();
		console.log('url', url);
		$.get({
			url: url,
			xhr: xhr,
			success: parseRegion,
		});
		
	}
	
	function parseRegion(data) {
		console.log('data', data);
	}
	
	function downloadConstituency() {
		if (constituencyURLs.length == 0) {
			return;
		}
		var url = constituencyURLs.shift();
		console.log('url', url);
		$.get(url, parseConstituency);
	}
	
	function parseConstituency(data) {
		console.log('data', data);
	}
	
	// hack: https://stackoverflow.com/questions/3372962/can-i-remove-the-x-requested-with-header-from-ajax-requests
	function xhr() {
		
		var unwantedHeaders = [
			'X-Requested-With',
			'Cookie',
			'Referer',
		];
		
        // Get new xhr object using default factory
        var xhr = jQuery.ajaxSettings.xhr();
		console.log('xhr', xhr);
        // Copy the browser's native setRequestHeader method
        var setRequestHeader = xhr.setRequestHeader;
        // Replace with a wrapper
        xhr.setRequestHeader = function(name, value) {
			console.log('setRequestHeader', name, value);
            // Ignore the X-Requested-With header
            if (unwantedHeaders.indexOf(name) >= 0) return;
            // Otherwise call the native setRequestHeader method
            // Note: setRequestHeader requires its 'this' to be the xhr object,
            // which is what 'this' is here when executed.
            setRequestHeader.call(this, name, value);
        }
        // pass it on to jQuery
        return xhr;
    }
	*/
	
	function getConstituencies() {
		var constituencies = [
			{slug: "aberafan-maesteg", name: "Aberafan Maesteg"},
			{slug: "aberdeen-north", name: "Aberdeen North"},
			{slug: "aberdeen-south", name: "Aberdeen South"},
			{slug: "aberdeenshire-north-and-moray-east", name: "Aberdeenshire North and Moray East"},
			{slug: "airdrie-and-shotts", name: "Airdrie and Shotts"},
			{slug: "aldershot", name: "Aldershot"},
			{slug: "aldridge-brownhills", name: "Aldridge-Brownhills"},
			{slug: "alloa-and-grangemouth", name: "Alloa and Grangemouth"},
			{slug: "altrincham-and-sale-west", name: "Altrincham and Sale West"},
			{slug: "alyn-and-deeside", name: "Alyn and Deeside"},
			{slug: "amber-valley", name: "Amber Valley"},
			{slug: "angus-and-perthshire-glens", name: "Angus and Perthshire Glens"},
			{slug: "arbroath-and-broughty-ferry", name: "Arbroath and Broughty Ferry"},
			{slug: "argyll-bute-and-south-lochaber", name: "Argyll, Bute and South Lochaber"},
			{slug: "arundel-and-south-downs", name: "Arundel and South Downs"},
			{slug: "ashfield", name: "Ashfield"},
			{slug: "ashford", name: "Ashford"},
			{slug: "ashton-under-lyne", name: "Ashton-under-Lyne"},
			{slug: "aylesbury", name: "Aylesbury"},
			{slug: "ayr-carrick-and-cumnock", name: "Ayr, Carrick and Cumnock"},
			{slug: "banbury", name: "Banbury"},
			{slug: "bangor-aberconwy", name: "Bangor Aberconwy"},
			{slug: "barking", name: "Barking"},
			{slug: "barnsley-north", name: "Barnsley North"},
			{slug: "barnsley-south", name: "Barnsley South"},
			{slug: "barrow-and-furness", name: "Barrow and Furness"},
			{slug: "basildon-and-billericay", name: "Basildon and Billericay"},
			{slug: "basingstoke", name: "Basingstoke"},
			{slug: "bassetlaw", name: "Bassetlaw"},
			{slug: "bath", name: "Bath"},
			{slug: "bathgate-and-linlithgow", name: "Bathgate and Linlithgow"},
			{slug: "battersea", name: "Battersea"},
			{slug: "beaconsfield", name: "Beaconsfield"},
			{slug: "beckenham-and-penge", name: "Beckenham and Penge"},
			{slug: "bedford", name: "Bedford"},
			{slug: "bermondsey-and-old-southwark", name: "Bermondsey and Old Southwark"},
			{slug: "berwickshire-roxburgh-and-selkirk", name: "Berwickshire, Roxburgh and Selkirk"},
			{slug: "bethnal-green-and-stepney", name: "Bethnal Green and Stepney"},
			{slug: "beverley-and-holderness", name: "Beverley and Holderness"},
			{slug: "bexhill-and-battle", name: "Bexhill and Battle"},
			{slug: "bexleyheath-and-crayford", name: "Bexleyheath and Crayford"},
			{slug: "bicester-and-woodstock", name: "Bicester and Woodstock"},
			{slug: "birkenhead", name: "Birkenhead"},
			{slug: "birmingham-edgbaston", name: "Birmingham Edgbaston"},
			{slug: "birmingham-erdington", name: "Birmingham Erdington"},
			{slug: "birmingham-hall-green-and-moseley", name: "Birmingham Hall Green and Moseley"},
			{slug: "birmingham-hodge-hill-and-solihull-north", name: "Birmingham Hodge Hill and Solihull North"},
			{slug: "birmingham-ladywood", name: "Birmingham Ladywood"},
			{slug: "birmingham-northfield", name: "Birmingham Northfield"},
			{slug: "birmingham-perry-barr", name: "Birmingham Perry Barr"},
			{slug: "birmingham-selly-oak", name: "Birmingham Selly Oak"},
			{slug: "birmingham-yardley", name: "Birmingham Yardley"},
			{slug: "bishop-auckland", name: "Bishop Auckland"},
			{slug: "blackburn", name: "Blackburn"},
			{slug: "blackley-and-middleton-south", name: "Blackley and Middleton South"},
			{slug: "blackpool-north-and-fleetwood", name: "Blackpool North and Fleetwood"},
			{slug: "blackpool-south", name: "Blackpool South"},
			{slug: "blaenau-gwent-and-rhymney", name: "Blaenau Gwent and Rhymney"},
			{slug: "blaydon-and-consett", name: "Blaydon and Consett"},
			{slug: "blyth-and-ashington", name: "Blyth and Ashington"},
			{slug: "bognor-regis-and-littlehampton", name: "Bognor Regis and Littlehampton"},
			{slug: "bolsover", name: "Bolsover"},
			{slug: "bolton-north-east", name: "Bolton North East"},
			{slug: "bolton-south-and-walkden", name: "Bolton South and Walkden"},
			{slug: "bolton-west", name: "Bolton West"},
			{slug: "bootle", name: "Bootle"},
			{slug: "boston-and-skegness", name: "Boston and Skegness"},
			{slug: "bournemouth-east", name: "Bournemouth East"},
			{slug: "bournemouth-west", name: "Bournemouth West"},
			{slug: "bracknell", name: "Bracknell"},
			{slug: "bradford-east", name: "Bradford East"},
			{slug: "bradford-south", name: "Bradford South"},
			{slug: "bradford-west", name: "Bradford West"},
			{slug: "braintree", name: "Braintree"},
			{slug: "brecon-radnor-and-cwm-tawe", name: "Brecon, Radnor and Cwm Tawe"},
			{slug: "brent-east", name: "Brent East"},
			{slug: "brent-west", name: "Brent West"},
			{slug: "brentford-and-isleworth", name: "Brentford and Isleworth"},
			{slug: "brentwood-and-ongar", name: "Brentwood and Ongar"},
			{slug: "bridgend", name: "Bridgend"},
			{slug: "bridgwater", name: "Bridgwater"},
			{slug: "bridlington-and-the-wolds", name: "Bridlington and The Wolds"},
			{slug: "brigg-and-immingham", name: "Brigg and Immingham"},
			{slug: "brighton-kemptown-and-peacehaven", name: "Brighton Kemptown and Peacehaven"},
			{slug: "brighton-pavilion", name: "Brighton Pavilion"},
			{slug: "bristol-central", name: "Bristol Central"},
			{slug: "bristol-east", name: "Bristol East"},
			{slug: "bristol-north-east", name: "Bristol North East"},
			{slug: "bristol-north-west", name: "Bristol North West"},
			{slug: "bristol-south", name: "Bristol South"},
			{slug: "broadland-and-fakenham", name: "Broadland and Fakenham"},
			{slug: "bromley-and-biggin-hill", name: "Bromley and Biggin Hill"},
			{slug: "bromsgrove", name: "Bromsgrove"},
			{slug: "broxbourne", name: "Broxbourne"},
			{slug: "broxtowe", name: "Broxtowe"},
			{slug: "buckingham-and-bletchley", name: "Buckingham and Bletchley"},
			{slug: "burnley", name: "Burnley"},
			{slug: "burton-and-uttoxeter", name: "Burton and Uttoxeter"},
			{slug: "bury-north", name: "Bury North"},
			{slug: "bury-south", name: "Bury South"},
			{slug: "bury-st-edmunds-and-stowmarket", name: "Bury St Edmunds and Stowmarket"},
			{slug: "caerfyrddin", name: "Caerfyrddin"},
			{slug: "caerphilly", name: "Caerphilly"},
			{slug: "caithness-sutherland-and-easter-ross", name: "Caithness, Sutherland and Easter Ross"},
			{slug: "calder-valley", name: "Calder Valley"},
			{slug: "camborne-and-redruth", name: "Camborne and Redruth"},
			{slug: "cambridge", name: "Cambridge"},
			{slug: "cannock-chase", name: "Cannock Chase"},
			{slug: "canterbury", name: "Canterbury"},
			{slug: "cardiff-east", name: "Cardiff East"},
			{slug: "cardiff-north", name: "Cardiff North"},
			{slug: "cardiff-south-and-penarth", name: "Cardiff South and Penarth"},
			{slug: "cardiff-west", name: "Cardiff West"},
			{slug: "carlisle", name: "Carlisle"},
			{slug: "carshalton-and-wallington", name: "Carshalton and Wallington"},
			{slug: "castle-point", name: "Castle Point"},
			{slug: "central-ayrshire", name: "Central Ayrshire"},
			{slug: "central-devon", name: "Central Devon"},
			{slug: "central-suffolk-and-north-ipswich", name: "Central Suffolk and North Ipswich"},
			{slug: "ceredigion-preseli", name: "Ceredigion Preseli"},
			{slug: "chatham-and-aylesford", name: "Chatham and Aylesford"},
			{slug: "cheadle", name: "Cheadle"},
			{slug: "chelmsford", name: "Chelmsford"},
			{slug: "chelsea-and-fulham", name: "Chelsea and Fulham"},
			{slug: "cheltenham", name: "Cheltenham"},
			{slug: "chesham-and-amersham", name: "Chesham and Amersham"},
			{slug: "chester-north-and-neston", name: "Chester North and Neston"},
			{slug: "chester-south-and-eddisbury", name: "Chester South and Eddisbury"},
			{slug: "chesterfield", name: "Chesterfield"},
			{slug: "chichester", name: "Chichester"},
			{slug: "chingford-and-woodford-green", name: "Chingford and Woodford Green"},
			{slug: "chippenham", name: "Chippenham"},
			{slug: "chipping-barnet", name: "Chipping Barnet"},
			{slug: "chorley", name: "Chorley"},
			{slug: "christchurch", name: "Christchurch"},
			{slug: "cities-of-london-and-westminster", name: "Cities of London and Westminster"},
			{slug: "city-of-durham", name: "City of Durham"},
			{slug: "clacton", name: "Clacton"},
			{slug: "clapham-and-brixton-hill", name: "Clapham and Brixton Hill"},
			{slug: "clwyd-east", name: "Clwyd East"},
			{slug: "clwyd-north", name: "Clwyd North"},
			{slug: "coatbridge-and-bellshill", name: "Coatbridge and Bellshill"},
			{slug: "colchester", name: "Colchester"},
			{slug: "colne-valley", name: "Colne Valley"},
			{slug: "congleton", name: "Congleton"},
			{slug: "corby-and-east-northamptonshire", name: "Corby and East Northamptonshire"},
			{slug: "coventry-east", name: "Coventry East"},
			{slug: "coventry-north-west", name: "Coventry North West"},
			{slug: "coventry-south", name: "Coventry South"},
			{slug: "cowdenbeath-and-kirkcaldy", name: "Cowdenbeath and Kirkcaldy"},
			{slug: "cramlington-and-killingworth", name: "Cramlington and Killingworth"},
			{slug: "crawley", name: "Crawley"},
			{slug: "crewe-and-nantwich", name: "Crewe and Nantwich"},
			{slug: "croydon-east", name: "Croydon East"},
			{slug: "croydon-south", name: "Croydon South"},
			{slug: "croydon-west", name: "Croydon West"},
			{slug: "cumbernauld-and-kirkintilloch", name: "Cumbernauld and Kirkintilloch"},
			{slug: "dagenham-and-rainham", name: "Dagenham and Rainham"},
			{slug: "darlington", name: "Darlington"},
			{slug: "dartford", name: "Dartford"},
			{slug: "daventry", name: "Daventry"},
			{slug: "derby-north", name: "Derby North"},
			{slug: "derby-south", name: "Derby South"},
			{slug: "derbyshire-dales", name: "Derbyshire Dales"},
			{slug: "dewsbury-and-batley", name: "Dewsbury and Batley"},
			{slug: "didcot-and-wantage", name: "Didcot and Wantage"},
			{slug: "doncaster-central", name: "Doncaster Central"},
			{slug: "doncaster-east-and-the-isle-of-axholme", name: "Doncaster East and the Isle of Axholme"},
			{slug: "doncaster-north", name: "Doncaster North"},
			{slug: "dorking-and-horley", name: "Dorking and Horley"},
			{slug: "dover-and-deal", name: "Dover and Deal"},
			{slug: "droitwich-and-evesham", name: "Droitwich and Evesham"},
			{slug: "dudley", name: "Dudley"},
			{slug: "dulwich-and-west-norwood", name: "Dulwich and West Norwood"},
			{slug: "dumfries-and-galloway", name: "Dumfries and Galloway"},
			{slug: "dumfriesshire-clydesdale-and-tweeddale", name: "Dumfriesshire, Clydesdale and Tweeddale"},
			{slug: "dundee-central", name: "Dundee Central"},
			{slug: "dunfermline-and-dollar", name: "Dunfermline and Dollar"},
			{slug: "dunstable-and-leighton-buzzard", name: "Dunstable and Leighton Buzzard"},
			{slug: "dwyfor-meirionnydd", name: "Dwyfor Meirionnydd"},
			{slug: "ealing-central-and-acton", name: "Ealing Central and Acton"},
			{slug: "ealing-north", name: "Ealing North"},
			{slug: "ealing-southall", name: "Ealing Southall"},
			{slug: "earley-and-woodley", name: "Earley and Woodley"},
			{slug: "easington", name: "Easington"},
			{slug: "east-grinstead-and-uckfield", name: "East Grinstead and Uckfield"},
			{slug: "east-ham", name: "East Ham"},
			{slug: "east-hampshire", name: "East Hampshire"},
			{slug: "east-kilbride-and-strathaven", name: "East Kilbride and Strathaven"},
			{slug: "east-renfrewshire", name: "East Renfrewshire"},
			{slug: "east-surrey", name: "East Surrey"},
			{slug: "east-thanet", name: "East Thanet"},
			{slug: "east-wiltshire", name: "East Wiltshire"},
			{slug: "east-worthing-and-shoreham", name: "East Worthing and Shoreham"},
			{slug: "eastbourne", name: "Eastbourne"},
			{slug: "eastleigh", name: "Eastleigh"},
			{slug: "edinburgh-east-and-musselburgh", name: "Edinburgh East and Musselburgh"},
			{slug: "edinburgh-north-and-leith", name: "Edinburgh North and Leith"},
			{slug: "edinburgh-south", name: "Edinburgh South"},
			{slug: "edinburgh-south-west", name: "Edinburgh South West"},
			{slug: "edinburgh-west", name: "Edinburgh West"},
			{slug: "edmonton-and-winchmore-hill", name: "Edmonton and Winchmore Hill"},
			{slug: "ellesmere-port-and-bromborough", name: "Ellesmere Port and Bromborough"},
			{slug: "eltham-and-chislehurst", name: "Eltham and Chislehurst"},
			{slug: "ely-and-east-cambridgeshire", name: "Ely and East Cambridgeshire"},
			{slug: "enfield-north", name: "Enfield North"},
			{slug: "epping-forest", name: "Epping Forest"},
			{slug: "epsom-and-ewell", name: "Epsom and Ewell"},
			{slug: "erewash", name: "Erewash"},
			{slug: "erith-and-thamesmead", name: "Erith and Thamesmead"},
			{slug: "esher-and-walton", name: "Esher and Walton"},
			{slug: "exeter", name: "Exeter"},
			{slug: "exmouth-and-exeter-east", name: "Exmouth and Exeter East"},
			{slug: "falkirk", name: "Falkirk"},
			{slug: "fareham-and-waterlooville", name: "Fareham and Waterlooville"},
			{slug: "farnham-and-bordon", name: "Farnham and Bordon"},
			{slug: "faversham-and-mid-kent", name: "Faversham and Mid Kent"},
			{slug: "feltham-and-heston", name: "Feltham and Heston"},
			{slug: "filton-and-bradley-stoke", name: "Filton and Bradley Stoke"},
			{slug: "finchley-and-golders-green", name: "Finchley and Golders Green"},
			{slug: "folkestone-and-hythe", name: "Folkestone and Hythe"},
			{slug: "forest-of-dean", name: "Forest of Dean"},
			{slug: "frome-and-east-somerset", name: "Frome and East Somerset"},
			{slug: "fylde", name: "Fylde"},
			{slug: "gainsborough", name: "Gainsborough"},
			{slug: "gateshead-central-and-whickham", name: "Gateshead Central and Whickham"},
			{slug: "gedling", name: "Gedling"},
			{slug: "gillingham-and-rainham", name: "Gillingham and Rainham"},
			{slug: "glasgow-east", name: "Glasgow East"},
			{slug: "glasgow-north", name: "Glasgow North"},
			{slug: "glasgow-north-east", name: "Glasgow North East"},
			{slug: "glasgow-south", name: "Glasgow South"},
			{slug: "glasgow-south-west", name: "Glasgow South West"},
			{slug: "glasgow-west", name: "Glasgow West"},
			{slug: "glastonbury-and-somerton", name: "Glastonbury and Somerton"},
			{slug: "glenrothes-and-mid-fife", name: "Glenrothes and Mid Fife"},
			{slug: "gloucester", name: "Gloucester"},
			{slug: "godalming-and-ash", name: "Godalming and Ash"},
			{slug: "goole-and-pocklington", name: "Goole and Pocklington"},
			{slug: "gordon-and-buchan", name: "Gordon and Buchan"},
			{slug: "gorton-and-denton", name: "Gorton and Denton"},
			{slug: "gosport", name: "Gosport"},
			{slug: "gower", name: "Gower"},
			{slug: "grantham-and-bourne", name: "Grantham and Bourne"},
			{slug: "gravesham", name: "Gravesham"},
			{slug: "great-grimsby-and-cleethorpes", name: "Great Grimsby and Cleethorpes"},
			{slug: "great-yarmouth", name: "Great Yarmouth"},
			{slug: "greenwich-and-woolwich", name: "Greenwich and Woolwich"},
			{slug: "guildford", name: "Guildford"},
			{slug: "hackney-north-and-stoke-newington", name: "Hackney North and Stoke Newington"},
			{slug: "hackney-south-and-shoreditch", name: "Hackney South and Shoreditch"},
			{slug: "halesowen", name: "Halesowen"},
			{slug: "halifax", name: "Halifax"},
			{slug: "hamble-valley", name: "Hamble Valley"},
			{slug: "hamilton-and-clyde-valley", name: "Hamilton and Clyde Valley"},
			{slug: "hammersmith-and-chiswick", name: "Hammersmith and Chiswick"},
			{slug: "hampstead-and-highgate", name: "Hampstead and Highgate"},
			{slug: "harborough-oadby-and-wigston", name: "Harborough, Oadby and Wigston"},
			{slug: "harlow", name: "Harlow"},
			{slug: "harpenden-and-berkhamsted", name: "Harpenden and Berkhamsted"},
			{slug: "harrogate-and-knaresborough", name: "Harrogate and Knaresborough"},
			{slug: "harrow-east", name: "Harrow East"},
			{slug: "harrow-west", name: "Harrow West"},
			{slug: "hartlepool", name: "Hartlepool"},
			{slug: "harwich-and-north-essex", name: "Harwich and North Essex"},
			{slug: "hastings-and-rye", name: "Hastings and Rye"},
			{slug: "havant", name: "Havant"},
			{slug: "hayes-and-harlington", name: "Hayes and Harlington"},
			{slug: "hazel-grove", name: "Hazel Grove"},
			{slug: "hemel-hempstead", name: "Hemel Hempstead"},
			{slug: "hendon", name: "Hendon"},
			{slug: "henley-and-thame", name: "Henley and Thame"},
			{slug: "hereford-and-south-herefordshire", name: "Hereford and South Herefordshire"},
			{slug: "herne-bay-and-sandwich", name: "Herne Bay and Sandwich"},
			{slug: "hertford-and-stortford", name: "Hertford and Stortford"},
			{slug: "hertsmere", name: "Hertsmere"},
			{slug: "hexham", name: "Hexham"},
			{slug: "heywood-and-middleton-north", name: "Heywood and Middleton North"},
			{slug: "high-peak", name: "High Peak"},
			{slug: "hinckley-and-bosworth", name: "Hinckley and Bosworth"},
			{slug: "hitchin", name: "Hitchin"},
			{slug: "holborn-and-st-pancras", name: "Holborn and St Pancras"},
			{slug: "honiton-and-sidmouth", name: "Honiton and Sidmouth"},
			{slug: "hornchurch-and-upminster", name: "Hornchurch and Upminster"},
			{slug: "hornsey-and-friern-barnet", name: "Hornsey and Friern Barnet"},
			{slug: "horsham", name: "Horsham"},
			{slug: "houghton-and-sunderland-south", name: "Houghton and Sunderland South"},
			{slug: "hove-and-portslade", name: "Hove and Portslade"},
			{slug: "huddersfield", name: "Huddersfield"},
			{slug: "huntingdon", name: "Huntingdon"},
			{slug: "hyndburn", name: "Hyndburn"},
			{slug: "ilford-north", name: "Ilford North"},
			{slug: "ilford-south", name: "Ilford South"},
			{slug: "inverclyde-and-renfrewshire-west", name: "Inverclyde and Renfrewshire West"},
			{slug: "inverness-skye-and-west-ross-shire", name: "Inverness, Skye and West Ross-shire"},
			{slug: "ipswich", name: "Ipswich"},
			{slug: "isle-of-wight-east", name: "Isle of Wight East"},
			{slug: "isle-of-wight-west", name: "Isle of Wight West"},
			{slug: "islington-north", name: "Islington North"},
			{slug: "islington-south-and-finsbury", name: "Islington South and Finsbury"},
			{slug: "jarrow-and-gateshead-east", name: "Jarrow and Gateshead East"},
			{slug: "keighley-and-ilkley", name: "Keighley and Ilkley"},
			{slug: "kenilworth-and-southam", name: "Kenilworth and Southam"},
			{slug: "kensington-and-bayswater", name: "Kensington and Bayswater"},
			{slug: "kettering", name: "Kettering"},
			{slug: "kilmarnock-and-loudoun", name: "Kilmarnock and Loudoun"},
			{slug: "kingston-and-surbiton", name: "Kingston and Surbiton"},
			{slug: "kingston-upon-hull-east", name: "Kingston upon Hull East"},
			{slug: "kingston-upon-hull-north-and-cottingham", name: "Kingston upon Hull North and Cottingham"},
			{slug: "kingston-upon-hull-west-and-haltemprice", name: "Kingston upon Hull West and Haltemprice"},
			{slug: "kingswinford-and-south-staffordshire", name: "Kingswinford and South Staffordshire"},
			{slug: "knowsley", name: "Knowsley"},
			{slug: "lancaster-and-wyre", name: "Lancaster and Wyre"},
			{slug: "leeds-central-and-headingley", name: "Leeds Central and Headingley"},
			{slug: "leeds-east", name: "Leeds East"},
			{slug: "leeds-north-east", name: "Leeds North East"},
			{slug: "leeds-north-west", name: "Leeds North West"},
			{slug: "leeds-south", name: "Leeds South"},
			{slug: "leeds-south-west-and-morley", name: "Leeds South West and Morley"},
			{slug: "leeds-west-and-pudsey", name: "Leeds West and Pudsey"},
			{slug: "leicester-east", name: "Leicester East"},
			{slug: "leicester-south", name: "Leicester South"},
			{slug: "leicester-west", name: "Leicester West"},
			{slug: "leigh-and-atherton", name: "Leigh and Atherton"},
			{slug: "lewes", name: "Lewes"},
			{slug: "lewisham-east", name: "Lewisham East"},
			{slug: "lewisham-north", name: "Lewisham North"},
			{slug: "lewisham-west-and-east-dulwich", name: "Lewisham West and East Dulwich"},
			{slug: "leyton-and-wanstead", name: "Leyton and Wanstead"},
			{slug: "lichfield", name: "Lichfield"},
			{slug: "lincoln", name: "Lincoln"},
			{slug: "liverpool-garston", name: "Liverpool Garston"},
			{slug: "liverpool-riverside", name: "Liverpool Riverside"},
			{slug: "liverpool-walton", name: "Liverpool Walton"},
			{slug: "liverpool-wavertree", name: "Liverpool Wavertree"},
			{slug: "liverpool-west-derby", name: "Liverpool West Derby"},
			{slug: "livingston", name: "Livingston"},
			{slug: "llanelli", name: "Llanelli"},
			{slug: "lothian-east", name: "Lothian East"},
			{slug: "loughborough", name: "Loughborough"},
			{slug: "louth-and-horncastle", name: "Louth and Horncastle"},
			{slug: "lowestoft", name: "Lowestoft"},
			{slug: "luton-north", name: "Luton North"},
			{slug: "luton-south-and-south-bedfordshire", name: "Luton South and South Bedfordshire"},
			{slug: "macclesfield", name: "Macclesfield"},
			{slug: "maidenhead", name: "Maidenhead"},
			{slug: "maidstone-and-malling", name: "Maidstone and Malling"},
			{slug: "makerfield", name: "Makerfield"},
			{slug: "maldon", name: "Maldon"},
			{slug: "manchester-central", name: "Manchester Central"},
			{slug: "manchester-rusholme", name: "Manchester Rusholme"},
			{slug: "manchester-withington", name: "Manchester Withington"},
			{slug: "mansfield", name: "Mansfield"},
			{slug: "melksham-and-devizes", name: "Melksham and Devizes"},
			{slug: "melton-and-syston", name: "Melton and Syston"},
			{slug: "meriden-and-solihull-east", name: "Meriden and Solihull East"},
			{slug: "merthyr-tydfil-and-aberdare", name: "Merthyr Tydfil and Aberdare"},
			{slug: "mid-and-south-pembrokeshire", name: "Mid and South Pembrokeshire"},
			{slug: "mid-bedfordshire", name: "Mid Bedfordshire"},
			{slug: "mid-buckinghamshire", name: "Mid Buckinghamshire"},
			{slug: "mid-cheshire", name: "Mid Cheshire"},
			{slug: "mid-derbyshire", name: "Mid Derbyshire"},
			{slug: "mid-dorset-and-north-poole", name: "Mid Dorset and North Poole"},
			{slug: "mid-dunbartonshire", name: "Mid Dunbartonshire"},
			{slug: "mid-leicestershire", name: "Mid Leicestershire"},
			{slug: "mid-norfolk", name: "Mid Norfolk"},
			{slug: "mid-sussex", name: "Mid Sussex"},
			{slug: "middlesbrough-and-thornaby-east", name: "Middlesbrough and Thornaby East"},
			{slug: "middlesbrough-south-and-east-cleveland", name: "Middlesbrough South and East Cleveland"},
			{slug: "midlothian", name: "Midlothian"},
			{slug: "milton-keynes-central", name: "Milton Keynes Central"},
			{slug: "milton-keynes-north", name: "Milton Keynes North"},
			{slug: "mitcham-and-morden", name: "Mitcham and Morden"},
			{slug: "monmouthshire", name: "Monmouthshire"},
			{slug: "montgomeryshire-and-glyndwr", name: "Montgomeryshire and Glyndwr"},
			{slug: "moray-west-nairn-and-strathspey", name: "Moray West, Nairn and Strathspey"},
			{slug: "morecambe-and-lunesdale", name: "Morecambe and Lunesdale"},
			{slug: "motherwell-wishaw-and-carluke", name: "Motherwell, Wishaw and Carluke"},
			{slug: "na-h-eileanan-an-iar", name: "Na h-Eileanan an Iar"},
			{slug: "neath-and-swansea-east", name: "Neath and Swansea East"},
			{slug: "new-forest-east", name: "New Forest East"},
			{slug: "new-forest-west", name: "New Forest West"},
			{slug: "newark", name: "Newark"},
			{slug: "newbury", name: "Newbury"},
			{slug: "newcastle-upon-tyne-central-and-west", name: "Newcastle upon Tyne Central and West"},
			{slug: "newcastle-upon-tyne-east-and-wallsend", name: "Newcastle upon Tyne East and Wallsend"},
			{slug: "newcastle-upon-tyne-north", name: "Newcastle upon Tyne North"},
			{slug: "newcastle-under-lyme", name: "Newcastle-under-Lyme"},
			{slug: "newport-east", name: "Newport East"},
			{slug: "newport-west-and-islwyn", name: "Newport West and Islwyn"},
			{slug: "newton-abbot", name: "Newton Abbot"},
			{slug: "newton-aycliffe-and-spennymoor", name: "Newton Aycliffe and Spennymoor"},
			{slug: "normanton-and-hemsworth", name: "Normanton and Hemsworth"},
			{slug: "north-ayrshire-and-arran", name: "North Ayrshire and Arran"},
			{slug: "north-bedfordshire", name: "North Bedfordshire"},
			{slug: "north-cornwall", name: "North Cornwall"},
			{slug: "north-cotswolds", name: "North Cotswolds"},
			{slug: "north-devon", name: "North Devon"},
			{slug: "north-dorset", name: "North Dorset"},
			{slug: "north-durham", name: "North Durham"},
			{slug: "north-east-cambridgeshire", name: "North East Cambridgeshire"},
			{slug: "north-east-derbyshire", name: "North East Derbyshire"},
			{slug: "north-east-fife", name: "North East Fife"},
			{slug: "north-east-hampshire", name: "North East Hampshire"},
			{slug: "north-east-hertfordshire", name: "North East Hertfordshire"},
			{slug: "north-east-somerset-and-hanham", name: "North East Somerset and Hanham"},
			{slug: "north-herefordshire", name: "North Herefordshire"},
			{slug: "north-norfolk", name: "North Norfolk"},
			{slug: "north-northumberland", name: "North Northumberland"},
			{slug: "north-shropshire", name: "North Shropshire"},
			{slug: "north-somerset", name: "North Somerset"},
			{slug: "north-warwickshire-and-bedworth", name: "North Warwickshire and Bedworth"},
			{slug: "north-west-cambridgeshire", name: "North West Cambridgeshire"},
			{slug: "north-west-essex", name: "North West Essex"},
			{slug: "north-west-hampshire", name: "North West Hampshire"},
			{slug: "north-west-leicestershire", name: "North West Leicestershire"},
			{slug: "north-west-norfolk", name: "North West Norfolk"},
			{slug: "northampton-north", name: "Northampton North"},
			{slug: "northampton-south", name: "Northampton South"},
			{slug: "norwich-north", name: "Norwich North"},
			{slug: "norwich-south", name: "Norwich South"},
			{slug: "nottingham-east", name: "Nottingham East"},
			{slug: "nottingham-north-and-kimberley", name: "Nottingham North and Kimberley"},
			{slug: "nottingham-south", name: "Nottingham South"},
			{slug: "nuneaton", name: "Nuneaton"},
			{slug: "old-bexley-and-sidcup", name: "Old Bexley and Sidcup"},
			{slug: "oldham-east-and-saddleworth", name: "Oldham East and Saddleworth"},
			{slug: "oldham-west-chadderton-and-royton", name: "Oldham West, Chadderton and Royton"},
			{slug: "orkney-and-shetland", name: "Orkney and Shetland"},
			{slug: "orpington", name: "Orpington"},
			{slug: "ossett-and-denby-dale", name: "Ossett and Denby Dale"},
			{slug: "oxford-east", name: "Oxford East"},
			{slug: "oxford-west-and-abingdon", name: "Oxford West and Abingdon"},
			{slug: "paisley-and-renfrewshire-north", name: "Paisley and Renfrewshire North"},
			{slug: "paisley-and-renfrewshire-south", name: "Paisley and Renfrewshire South"},
			{slug: "peckham", name: "Peckham"},
			{slug: "pendle-and-clitheroe", name: "Pendle and Clitheroe"},
			{slug: "penistone-and-stocksbridge", name: "Penistone and Stocksbridge"},
			{slug: "penrith-and-solway", name: "Penrith and Solway"},
			{slug: "perth-and-kinross-shire", name: "Perth and Kinross-shire"},
			{slug: "peterborough", name: "Peterborough"},
			{slug: "plymouth-moor-view", name: "Plymouth Moor View"},
			{slug: "plymouth-sutton-and-devonport", name: "Plymouth Sutton and Devonport"},
			{slug: "pontefract-castleford-and-knottingley", name: "Pontefract, Castleford and Knottingley"},
			{slug: "pontypridd", name: "Pontypridd"},
			{slug: "poole", name: "Poole"},
			{slug: "poplar-and-limehouse", name: "Poplar and Limehouse"},
			{slug: "portsmouth-north", name: "Portsmouth North"},
			{slug: "portsmouth-south", name: "Portsmouth South"},
			{slug: "preston", name: "Preston"},
			{slug: "putney", name: "Putney"},
			{slug: "queens-park-and-maida-vale", name: "Queen's Park and Maida Vale"},
			{slug: "rawmarsh-and-conisbrough", name: "Rawmarsh and Conisbrough"},
			{slug: "rayleigh-and-wickford", name: "Rayleigh and Wickford"},
			{slug: "reading-central", name: "Reading Central"},
			{slug: "reading-west-and-mid-berkshire", name: "Reading West and Mid Berkshire"},
			{slug: "redcar", name: "Redcar"},
			{slug: "redditch", name: "Redditch"},
			{slug: "reigate", name: "Reigate"},
			{slug: "rhondda-and-ogmore", name: "Rhondda and Ogmore"},
			{slug: "ribble-valley", name: "Ribble Valley"},
			{slug: "richmond-and-northallerton", name: "Richmond and Northallerton"},
			{slug: "richmond-park", name: "Richmond Park"},
			{slug: "rochdale", name: "Rochdale"},
			{slug: "rochester-and-strood", name: "Rochester and Strood"},
			{slug: "romford", name: "Romford"},
			{slug: "romsey-and-southampton-north", name: "Romsey and Southampton North"},
			{slug: "rossendale-and-darwen", name: "Rossendale and Darwen"},
			{slug: "rother-valley", name: "Rother Valley"},
			{slug: "rotherham", name: "Rotherham"},
			{slug: "rugby", name: "Rugby"},
			{slug: "ruislip-northwood-and-pinner", name: "Ruislip, Northwood and Pinner"},
			{slug: "runcorn-and-helsby", name: "Runcorn and Helsby"},
			{slug: "runnymede-and-weybridge", name: "Runnymede and Weybridge"},
			{slug: "rushcliffe", name: "Rushcliffe"},
			{slug: "rutherglen", name: "Rutherglen"},
			{slug: "rutland-and-stamford", name: "Rutland and Stamford"},
			{slug: "salford", name: "Salford"},
			{slug: "salisbury", name: "Salisbury"},
			{slug: "scarborough-and-whitby", name: "Scarborough and Whitby"},
			{slug: "scunthorpe", name: "Scunthorpe"},
			{slug: "sefton-central", name: "Sefton Central"},
			{slug: "selby", name: "Selby"},
			{slug: "sevenoaks", name: "Sevenoaks"},
			{slug: "sheffield-brightside-and-hillsborough", name: "Sheffield Brightside and Hillsborough"},
			{slug: "sheffield-central", name: "Sheffield Central"},
			{slug: "sheffield-hallam", name: "Sheffield Hallam"},
			{slug: "sheffield-heeley", name: "Sheffield Heeley"},
			{slug: "sheffield-south-east", name: "Sheffield South East"},
			{slug: "sherwood-forest", name: "Sherwood Forest"},
			{slug: "shipley", name: "Shipley"},
			{slug: "shrewsbury", name: "Shrewsbury"},
			{slug: "sittingbourne-and-sheppey", name: "Sittingbourne and Sheppey"},
			{slug: "skipton-and-ripon", name: "Skipton and Ripon"},
			{slug: "sleaford-and-north-hykeham", name: "Sleaford and North Hykeham"},
			{slug: "slough", name: "Slough"},
			{slug: "smethwick", name: "Smethwick"},
			{slug: "solihull-west-and-shirley", name: "Solihull West and Shirley"},
			{slug: "south-basildon-and-east-thurrock", name: "South Basildon and East Thurrock"},
			{slug: "south-cambridgeshire", name: "South Cambridgeshire"},
			{slug: "south-cotswolds", name: "South Cotswolds"},
			{slug: "south-derbyshire", name: "South Derbyshire"},
			{slug: "south-devon", name: "South Devon"},
			{slug: "south-dorset", name: "South Dorset"},
			{slug: "south-east-cornwall", name: "South East Cornwall"},
			{slug: "south-holland-and-the-deepings", name: "South Holland and the Deepings"},
			{slug: "south-leicestershire", name: "South Leicestershire"},
			{slug: "south-norfolk", name: "South Norfolk"},
			{slug: "south-northamptonshire", name: "South Northamptonshire"},
			{slug: "south-ribble", name: "South Ribble"},
			{slug: "south-shields", name: "South Shields"},
			{slug: "south-shropshire", name: "South Shropshire"},
			{slug: "south-suffolk", name: "South Suffolk"},
			{slug: "south-west-devon", name: "South West Devon"},
			{slug: "south-west-hertfordshire", name: "South West Hertfordshire"},
			{slug: "south-west-norfolk", name: "South West Norfolk"},
			{slug: "south-west-wiltshire", name: "South West Wiltshire"},
			{slug: "southampton-itchen", name: "Southampton Itchen"},
			{slug: "southampton-test", name: "Southampton Test"},
			{slug: "southend-east-and-rochford", name: "Southend East and Rochford"},
			{slug: "southend-west-and-leigh", name: "Southend West and Leigh"},
			{slug: "southgate-and-wood-green", name: "Southgate and Wood Green"},
			{slug: "southport", name: "Southport"},
			{slug: "spelthorne", name: "Spelthorne"},
			{slug: "spen-valley", name: "Spen Valley"},
			{slug: "st-albans", name: "St Albans"},
			{slug: "st-austell-and-newquay", name: "St Austell and Newquay"},
			{slug: "st-helens-north", name: "St Helens North"},
			{slug: "st-helens-south-and-whiston", name: "St Helens South and Whiston"},
			{slug: "st-ives", name: "St Ives"},
			{slug: "st-neots-and-mid-cambridgeshire", name: "St Neots and Mid Cambridgeshire"},
			{slug: "stafford", name: "Stafford"},
			{slug: "staffordshire-moorlands", name: "Staffordshire Moorlands"},
			{slug: "stalybridge-and-hyde", name: "Stalybridge and Hyde"},
			{slug: "stevenage", name: "Stevenage"},
			{slug: "stirling-and-strathallan", name: "Stirling and Strathallan"},
			{slug: "stockport", name: "Stockport"},
			{slug: "stockton-north", name: "Stockton North"},
			{slug: "stockton-west", name: "Stockton West"},
			{slug: "stoke-on-trent-central", name: "Stoke-on-Trent Central"},
			{slug: "stoke-on-trent-north", name: "Stoke-on-Trent North"},
			{slug: "stoke-on-trent-south", name: "Stoke-on-Trent South"},
			{slug: "stone-great-wyrley-and-penkridge", name: "Stone, Great Wyrley and Penkridge"},
			{slug: "stourbridge", name: "Stourbridge"},
			{slug: "stratford-and-bow", name: "Stratford and Bow"},
			{slug: "stratford-on-avon", name: "Stratford-on-Avon"},
			{slug: "streatham-and-croydon-north", name: "Streatham and Croydon North"},
			{slug: "stretford-and-urmston", name: "Stretford and Urmston"},
			{slug: "stroud", name: "Stroud"},
			{slug: "suffolk-coastal", name: "Suffolk Coastal"},
			{slug: "sunderland-central", name: "Sunderland Central"},
			{slug: "surrey-heath", name: "Surrey Heath"},
			{slug: "sussex-weald", name: "Sussex Weald"},
			{slug: "sutton-and-cheam", name: "Sutton and Cheam"},
			{slug: "sutton-coldfield", name: "Sutton Coldfield"},
			{slug: "swansea-west", name: "Swansea West"},
			{slug: "swindon-north", name: "Swindon North"},
			{slug: "swindon-south", name: "Swindon South"},
			{slug: "tamworth", name: "Tamworth"},
			{slug: "tatton", name: "Tatton"},
			{slug: "taunton-and-wellington", name: "Taunton and Wellington"},
			{slug: "telford", name: "Telford"},
			{slug: "tewkesbury", name: "Tewkesbury"},
			{slug: "the-wrekin", name: "The Wrekin"},
			{slug: "thirsk-and-malton", name: "Thirsk and Malton"},
			{slug: "thornbury-and-yate", name: "Thornbury and Yate"},
			{slug: "thurrock", name: "Thurrock"},
			{slug: "tipton-and-wednesbury", name: "Tipton and Wednesbury"},
			{slug: "tiverton-and-minehead", name: "Tiverton and Minehead"},
			{slug: "tonbridge", name: "Tonbridge"},
			{slug: "tooting", name: "Tooting"},
			{slug: "torbay", name: "Torbay"},
			{slug: "torfaen", name: "Torfaen"},
			{slug: "torridge-and-tavistock", name: "Torridge and Tavistock"},
			{slug: "tottenham", name: "Tottenham"},
			{slug: "truro-and-falmouth", name: "Truro and Falmouth"},
			{slug: "tunbridge-wells", name: "Tunbridge Wells"},
			{slug: "twickenham", name: "Twickenham"},
			{slug: "tynemouth", name: "Tynemouth"},
			{slug: "uxbridge-and-south-ruislip", name: "Uxbridge and South Ruislip"},
			{slug: "vale-of-glamorgan", name: "Vale of Glamorgan"},
			{slug: "vauxhall-and-camberwell-green", name: "Vauxhall and Camberwell Green"},
			{slug: "wakefield-and-rothwell", name: "Wakefield and Rothwell"},
			{slug: "wallasey", name: "Wallasey"},
			{slug: "walsall-and-bloxwich", name: "Walsall and Bloxwich"},
			{slug: "walthamstow", name: "Walthamstow"},
			{slug: "warrington-north", name: "Warrington North"},
			{slug: "warrington-south", name: "Warrington South"},
			{slug: "warwick-and-leamington", name: "Warwick and Leamington"},
			{slug: "washington-and-gateshead-south", name: "Washington and Gateshead South"},
			{slug: "watford", name: "Watford"},
			{slug: "waveney-valley", name: "Waveney Valley"},
			{slug: "weald-of-kent", name: "Weald of Kent"},
			{slug: "wellingborough-and-rushden", name: "Wellingborough and Rushden"},
			{slug: "wells-and-mendip-hills", name: "Wells and Mendip Hills"},
			{slug: "welwyn-hatfield", name: "Welwyn Hatfield"},
			{slug: "west-aberdeenshire-and-kincardine", name: "West Aberdeenshire and Kincardine"},
			{slug: "west-bromwich", name: "West Bromwich"},
			{slug: "west-dorset", name: "West Dorset"},
			{slug: "west-dunbartonshire", name: "West Dunbartonshire"},
			{slug: "west-ham-and-beckton", name: "West Ham and Beckton"},
			{slug: "west-lancashire", name: "West Lancashire"},
			{slug: "west-suffolk", name: "West Suffolk"},
			{slug: "west-worcestershire", name: "West Worcestershire"},
			{slug: "westmorland-and-lonsdale", name: "Westmorland and Lonsdale"},
			{slug: "weston-super-mare", name: "Weston-super-Mare"},
			{slug: "wetherby-and-easingwold", name: "Wetherby and Easingwold"},
			{slug: "whitehaven-and-workington", name: "Whitehaven and Workington"},
			{slug: "widnes-and-halewood", name: "Widnes and Halewood"},
			{slug: "wigan", name: "Wigan"},
			{slug: "wimbledon", name: "Wimbledon"},
			{slug: "winchester", name: "Winchester"},
			{slug: "windsor", name: "Windsor"},
			{slug: "wirral-west", name: "Wirral West"},
			{slug: "witham", name: "Witham"},
			{slug: "witney", name: "Witney"},
			{slug: "woking", name: "Woking"},
			{slug: "wokingham", name: "Wokingham"},
			{slug: "wolverhampton-north-east", name: "Wolverhampton North East"},
			{slug: "wolverhampton-south-east", name: "Wolverhampton South East"},
			{slug: "wolverhampton-west", name: "Wolverhampton West"},
			{slug: "worcester", name: "Worcester"},
			{slug: "worsley-and-eccles", name: "Worsley and Eccles"},
			{slug: "worthing-west", name: "Worthing West"},
			{slug: "wrexham", name: "Wrexham"},
			{slug: "wycombe", name: "Wycombe"},
			{slug: "wyre-forest", name: "Wyre Forest"},
			{slug: "wythenshawe-and-sale-east", name: "Wythenshawe and Sale East"},
			{slug: "yeovil", name: "Yeovil"},
			{slug: "ynys-mon", name: "Ynys Mon"},
			{slug: "york-central", name: "York Central"},
			{slug: "york-outer", name: "York Outer"},
		];
		return constituencies;
	}
	
});
})(jQuery);
