var Parties = {
	"Conservative and Unionist Party":          {abbr: "Con"},
	"Labour Party":                             {abbr: "Lab"},
	"Labour and Co-operative Party":            {abbr: "Lab"},
	"Liberal Democrats":                        {abbr: "LD"},
	"Green Party":                              {abbr: "Grn"},
	
	"For Future's Sake - Freedom Alliance":     {abbr: "Free"},
	"Social Democratic Party":                  {abbr: "SDP"},
	
	"Ashfield Independents":                    {abbr: "AshI"},
	"Ashford Independent":                      {abbr: "AshI"},
	"Barnsley Independent Group":               {abbr: "BIG"},
	"Wickford Independents":                    {abbr: "WickI"},
	"Basildon Community Residents Party":       {abbr: "BCR"},
	"Basingstoke & Deane Independents":         {abbr: "BDI"},
	"Farnworth and Kearsley First Party":       {abbr: "FKF"},
	"Westhoughton First Independents":          {abbr: "WFI"},
	"Bolton For Change":                        {abbr: "BFC"},
	"Horwich & Blackrod First Independents":    {abbr: "HBFI"},
	"Little Lever & Darcy Lever First":         {abbr: "LLDL"},
	"One Kearsley":                             {abbr: "OK"},
	"The Independent Choice":                   {abbr: "TIC"},
	"Poole Engage Party":                       {abbr: "PEP"},
	"The Party for Poole People Ltd.":          {abbr: "PPP"},
	"Christchurch Independents":                {abbr: "ChrI"},
	"Alliance For Local Living (ALL)":          {abbr: "ALL"},
	"Halstead Residents' Association":          {abbr: "HRA"},
	"Brighton & Hove Independents":             {abbr: "BHI"},
	"Wythall Residents' Association":           {abbr: "WRA"},
	"Burnley and Padiham independent Party":    {abbr: "BPI"},
	"Radcliffe First":                          {abbr: "RadF"},
	"Chase Community Independents Group":       {abbr: "CCIG"},
	"The People's Independent Party":           {abbr: "PIP"},
	"Canvey Island Independent Party":          {abbr: "CIIP"},
	"South Woodham Ferrers Council Taxpayers Association": {abbr: "SWF"},
	"Alderley Edge First":                      {abbr: "AEF"},
	"BollingtonFirst":                          {abbr: "BollF"},
	"Handforth 'Ratepayers' Association (Independent)": {abbr: "HRA"},
	"Residents of Wilmslow":                    {abbr: "RoW"},
	"Putting Crewe First, Independent Residents Group.": {abbr: "PCF"},
	"Chesterfield And North Derbyshire Independents (CANDI)": {abbr: "CANDI"},
	"Chichester and Harbour Independents":      {abbr: "CHI"},
	"Local Alliance":                           {abbr: "LA"},
	"Democracy for Chorley":                    {abbr: "DfC"},
	"Coventry Citizens Party":                  {abbr: "CCP"},
	"Reform Derby":                             {abbr: "Ref"},
	"Swanscombe and Greenhithe Residents' Association": {abbr: "SGRA"},
	"East Devon Alliance":                      {abbr: "EDA"},
	"Whitehill & Bordon Community Party":       {abbr: "WBC"},
	"Skegness urban district society":          {abbr: "SUDS"},
	"East Lindsey Independent Group":           {abbr: "ELIG"},
	"Esher Residents Association":              {abbr: "RA"},
	"Hersham Village Society":                  {abbr: "RA"},
	"Hinchley Wood Residents Association":      {abbr: "RA"},
	"Thames Ditton / Weston Green Residents' Association": {abbr: "RA"},
	"The Molesey Residents Association":        {abbr: "RA"},
	"The Walton Society":                       {abbr: "RA"},
	"Weybridge & St. George's Independents":    {abbr: "RA"},
	"Hinchley Wood / Weston Green Residents' Associations": {abbr: "RA"},
	"Independent Loughton Residents Association": {abbr: "ILRA"},
	"Residents Associations of Epsom and Ewell": {abbr: "RA"},
	"Ewell Court Residents' Association":       {abbr: "RA"},
	"Residents' Association of Cuddington":     {abbr: "RA"},
	"Stoneleigh and Auriol Residents' Association": {abbr: "RA"},
	"Fareham Independent Group":                {abbr: "FIG"},
	"Lytham St Annes Independents":             {abbr: "LSAI"},
	"Guildford Greenbelt Group":                {abbr: "GGG"},
	"Residents for Guildford and Villages":     {abbr: "RGV"},
	"Harlow Alliance Party":                    {abbr: "HAP"},
	"Community Campaign (Hart)":                {abbr: "CCH"},
	"Independent Union":                        {abbr: "IU"},
	"It's Our County (Herefordshire)":          {abbr: "IOC"},
	"Independent Alliance (Kent)":              {abbr: "IAK"},
	"Morecambe Bay Independents":               {abbr: "MBI"},
	"Garforth and Swillington Independents Party": {abbr: "GSI"},
	"Morley Borough Independents":              {abbr: "MBI"},
	"Save Our Beeston and Holbeck Independents": {abbr: "SBHI"},
	"Lincolnshire Independents Lincolnshire First": {abbr: "Lincs"},
	"Liverpool Community Independents":         {abbr: "LCI"},
	"Old Swan Against the Cuts":                {abbr: "OSAC"},
	"Mansfield Independents":                   {abbr: "ManI"},
	"The Maldon District Independent Group":    {abbr: "MDIG"},
	"Malvern Hills Independents":               {abbr: "MHI"},
	"Ashtead Independents":                     {abbr: "AshI"},
	"Newcastle Independents":                   {abbr: "NewI"},
	"Portishead Independents":                  {abbr: "PortI"},
	"Nottingham Independents":                  {abbr: "NottI"},
	"Proud of Oldham & Saddleworth":            {abbr: "POS"},
	"Failsworth Independent Party":             {abbr: "FIP"},
	"the Borough first Independents":           {abbr: "TBF"},
	
	"Independent":                              {abbr: "Ind"},
};
