var Parties = {
	
	"Conservative and Unionist Party":                              {abbr: "Con"},
	"Labour Party":                                                 {abbr: "Lab"},
	"Labour and Co-operative Party":                                {abbr: "Lab"},
	"Liberal Democrats":                                            {abbr: "LD"},
	"Green Party":                                                  {abbr: "Grn"},
	"Independent":                                                  {abbr: "Ind"},

	"Alliance for Democracy and Freedom":                           {abbr: "ADF"},
	"Animal Welfare Party":                                         {abbr: "AWP"},
	"Breakthrough Party":                                           {abbr: "Break"},
	"Britain First":                                                {abbr: "BritF"},
	"British Democratic Party":                                     {abbr: "BDP"},
	"British National Party":                                       {abbr: "BNP"},
	"Christian Peoples Alliance":                                   {abbr: "CPA"},
	"Communist Party of Britain":                                   {abbr: "CPB"},
	"English Constitution Party":                                   {abbr: "ECP"},
	"English Democrats":                                            {abbr: "ED"},
	"Five Star Direct Democracy Party":                             {abbr: "FSDD"},
	"For Future's Sake - Freedom Alliance":                         {abbr: "FA"},
	"Foundation Party":                                             {abbr: "Foun"},
	"Heritage Party":                                               {abbr: "Herit"},
	"Independent Network":                                          {abbr: "IndN"},
	"Libertarian Party":                                            {abbr: "Libt"},
	"National Front":                                               {abbr: "NF"},
	"National Health Action Party":                                 {abbr: "NHA"},
	"National Housing Party United Kingdom":                        {abbr: "NHP"},
	"Northern Heart":                                               {abbr: "NH"},
	"Northern Independence Party":                                  {abbr: "NIP"},
	"Patria":                                                       {abbr: "Pat"},
	"Psychedelic Movement":                                         {abbr: "Psych"},
	"Reform UK":                                                    {abbr: "Ref"},
	"Social Democratic Party":                                      {abbr: "SDP"},
	"Socialist Alternative":                                        {abbr: "Soc"},
	"Socialist Labour Party":                                       {abbr: "SLP"},
	"The Liberal Party":                                            {abbr: "Lib"},
	"The Moderate Group":                                           {abbr: "Mod"},
	"The North East Party":                                         {abbr: "NE"},
	"The Official Monster Raving Loony Party":                      {abbr: "Loony"},
	"The Peace Party - Non-violence, Justice, Environment":         {abbr: "Peace"},
	"The Socialist Party of Great Britain":                         {abbr: "SPGB"},
	"Trade Unionist and Socialist Coalition":                       {abbr: "TUSC"},
	"UK Independence Party (UKIP)":                                 {abbr: "UKIP"},
	"Veterans and People’s Party":                                  {abbr: "VAPP"},
	"Women's Equality Party":                                       {abbr: "WEP"},
	"Workers Party of Britain":                                     {abbr: "WPB"},
	"Yeshua":                                                       {abbr: "Yesh"},
	"Yorkshire Party":                                              {abbr: "Yorks"},

	"Belper Independents":                                          {abbr: "Belp"},
	"Ashfield Independents":                                        {abbr: "Ashf"},
	"Ashford Independent":                                          {abbr: "Ashf"},
	"Barnsley Independent Group":                                   {abbr: "BIG"},
	"Basildon Community Residents Party":                           {abbr: "BCR"},
	"Wickford Independents":                                        {abbr: "WickI"},
	"Basingstoke & Deane Independents":                             {abbr: "BDI"},
	"Bolton For Change":                                            {abbr: "BFC"},
	"Farnworth and Kearsley First Party":                           {abbr: "FKF"},
	"Horwich & Blackrod First Independents":                        {abbr: "HBFI"},
	"Little Lever & Darcy Lever First":                             {abbr: "LLDL"},
	"One Kearsley":                                                 {abbr: "OneK"},
	"The Independent Choice":                                       {abbr: "TIC"},
	"Westhoughton First Independents":                              {abbr: "WFI"},
	"Blue Revolution":                                              {abbr: "Blue"},
	"Boston Independent":                                           {abbr: "Bost"},
	"Alliance For Local Living (ALL)":                              {abbr: "ALL"},
	"Christchurch Independents":                                    {abbr: "Chr"},
	"Poole Engage Party":                                           {abbr: "PEP"},
	"The Party for Poole People Ltd.":                              {abbr: "PPP"},
	"Halstead Residents' Association":                              {abbr: "Halst"},
	"Brighton & Hove Independents":                                 {abbr: "BHI"},
	"Wythall Residents' Association":                               {abbr: "Wyth"},
	"Wycombe Independents":                                         {abbr: "Wyc"},
	"Burnley and Padiham independent Party":                        {abbr: "BPI"},
	"Radcliffe First":                                              {abbr: "RadF"},
	"Chase Community Independents Group":                           {abbr: "CCIG"},
	"Canvey Island Independent Party":                              {abbr: "CIIP"},
	"The People's Independent Party":                               {abbr: "PIP"},
	"South Woodham Ferrers Council Taxpayers Association":          {abbr: "SWF"},
	"Alderley Edge First":                                          {abbr: "AEF"},
	"BollingtonFirst":                                              {abbr: "BollF"},
	"Handforth 'Ratepayers' Association (Independent)":             {abbr: "HRA"},
	"Putting Crewe First, Independent Residents Group.":            {abbr: "PCF"},
	"Residents of Wilmslow":                                        {abbr: "RoW"},
	"Tytherington Ward Independents":                               {abbr: "Tyth"},
	"Chesterfield And North Derbyshire Independents (CANDI)":       {abbr: "CANDI"},
	"Chichester and Harbour Independents":                          {abbr: "CHI"},
	"Local Alliance":                                               {abbr: "LocA"},
	"Democracy for Chorley":                                        {abbr: "DfC"},
	"Coventry Citizens Party":                                      {abbr: "CCP"},
	"Swanscombe and Greenhithe Residents' Association":             {abbr: "SGRA"},
	"Reform Derby":                                                 {abbr: "Ref"},
	"Reform Derby and Reform UK":                                   {abbr: "Ref"},
	"East Devon Alliance":                                          {abbr: "EDA"},
	"Whitehill & Bordon Community Party":                           {abbr: "WBC"},
	"East Lindsey Independent Group":                               {abbr: "ELIG"},
	"Skegness urban district society":                              {abbr: "SUDS"},
	"Esher Residents Association":                                  {abbr: "RA"},
	"Hersham Village Society":                                      {abbr: "RA"},
	"Hinchley Wood / Weston Green Residents' Associations":         {abbr: "RA"},
	"Hinchley Wood Residents Association":                          {abbr: "RA"},
	"Thames Ditton / Weston Green Residents' Association":          {abbr: "RA"},
	"The Molesey Residents Association":                            {abbr: "RA"},
	"The Walton Society":                                           {abbr: "RA"},
	"Weybridge & St. George's Independents":                        {abbr: "RA"},
	"Independent Loughton Residents Association":                   {abbr: "ILRA"},
	"Ewell Court Residents' Association":                           {abbr: "RA"},
	"Residents Associations of Epsom and Ewell":                    {abbr: "RA"},
	"Residents' Association of Cuddington":                         {abbr: "RA"},
	"Stoneleigh and Auriol Residents' Association":                 {abbr: "RA"},
	"Fareham Independent Group":                                    {abbr: "FIG"},
	"Lytham St Annes Independents":                                 {abbr: "LSAI"},
	"Guildford Greenbelt Group":                                    {abbr: "GGG"},
	"Residents for Guildford and Villages":                         {abbr: "RGV"},
	"Hampshire Independents":                                       {abbr: "Hamp"},
	"Harlow Alliance Party":                                        {abbr: "HAP"},
	"Community Campaign (Hart)":                                    {abbr: "CCH"},
	"Independent Union":                                            {abbr: "IndU"},
	"It's Our County (Herefordshire)":                              {abbr: "IOC"},
	"Morecambe Bay Independents":                                   {abbr: "MBI"},
	"Alliance For Green Socialism":                                 {abbr: "AGS"},
	"Garforth and Swillington Independents Party":                  {abbr: "GSI"},
	"Morley Borough Independents":                                  {abbr: "MBI"},
	"Save Our Beeston and Holbeck Independents":                    {abbr: "SBHI"},
	"Lincolnshire Independents Lincolnshire First":                 {abbr: "Lincs"},
	"Liverpool Community Independents":                             {abbr: "LCI"},
	"Old Swan Against the Cuts":                                    {abbr: "OSAC"},
	"The Maldon District Independent Group":                        {abbr: "MDIG"},
	"Malvern Hills Independents":                                   {abbr: "MHI"},
	"Mansfield Independents":                                       {abbr: "Mans"},
	"Local First":                                                  {abbr: "Local"},
	"Ashtead Independents":                                         {abbr: "Asht"},
	"Newcastle Independents":                                       {abbr: "Newc"},
	"Portishead Independents":                                      {abbr: "Port"},
	"Nottingham Independents":                                      {abbr: "Nott"},
	"Failsworth Independent Party":                                 {abbr: "Fail"},
	"Proud of Oldham & Saddleworth":                                {abbr: "POS"},
	"Peterborough First":                                           {abbr: "PF"},
	"Active For Plymouth":                                          {abbr: "AfP"},
	"Change for Plymouth":                                          {abbr: "CfP"},
	"Portsmouth Independent Party":                                 {abbr: "PIP"},
	"East Cleveland Independent":                                   {abbr: "EClev"},
	"Nork Residents' Association":                                  {abbr: "NRA"},
	"Tattenham & Preston Residents":                                {abbr: "TPR"},
	"Middleton Independents Party":                                 {abbr: "MIP"},
	"Rochford District Residents":                                  {abbr: "Roch"},
	"Community First":                                              {abbr: "CF"},
	"Rother Association of Independent Councillors":                {abbr: "RAIC"},
	"Runnymede Independent Residents' Group":                       {abbr: "RIRG"},
	"Rushcliffe Independents":                                      {abbr: "Rush"},
	"Formby Residents Action Group":                                {abbr: "FRAG"},
	"Lydiate and Maghull Community Independents":                   {abbr: "LMCI"},
	"Hextable Independent":                                         {abbr: "HexI"},
	"Solihull and Meriden Residents Association":                   {abbr: "SMRA"},
	"South Holland Independents":                                   {abbr: "SHI"},
	"Henley Residents Group":                                       {abbr: "HRG"},
	"Confelicity":                                                  {abbr: "Conf"},
	"Stafford Borough Independents":                                {abbr: "SBI"},
	"Edgeley Community Association":                                {abbr: "ECA"},
	"Stockport Fights Austerity No to Cuts":                        {abbr: "SFA"},
	"Ingleby Barwick Independent Society":                          {abbr: "IBIS"},
	"Thornaby Independent Association":                             {abbr: "Thorn"},
	"City Independents":                                            {abbr: "City"},
	"Swale Independents":                                           {abbr: "Swale"},
	"Oxted & Limpsfield Residents Group":                           {abbr: "OLRG"},
	"Tandridge Residents Group":                                    {abbr: "TRG"},
	"South Devon Alliance":                                         {abbr: "SDA"},
	"Holland On Sea & Eastcliff Matters":                           {abbr: "HEM"},
	"Tendring First":                                               {abbr: "Tend"},
	"Andover Alliance":                                             {abbr: "AA"},
	"Tewkesbury and Twyning Independents":                          {abbr: "TTI"},
	"Thanet Independents":                                          {abbr: "Than"},
	"Thurrock Independents":                                        {abbr: "Thur"},
	"Independent Alliance (Kent)":                                  {abbr: "IAK"},
	"Royal Tunbridge Wells Residents Party":                        {abbr: "TWR"},
	"Tunbridge Wells Alliance":                                     {abbr: "TWA"},
	"Residents for Uttlesford":                                     {abbr: "R4U"},
	"Wakefield & District Independents":                            {abbr: "WDI"},
	"Whitnash Residents Association":                               {abbr: "WRA"},
	"Farnham Residents":                                            {abbr: "Farn"},
	"Welwyn Garden City Party":                                     {abbr: "WGCP"},
	"Our West Lancashire":                                          {abbr: "OWL"},
	"Skelmersdale Independent Party":                               {abbr: "Skem"},
	"West Suffolk Independents":                                    {abbr: "WSI"},
	"Leigh & Atherton Independents":                                {abbr: "LAI"},
	"Standish Independents":                                        {abbr: "Stand"},
	"Wigan Independents":                                           {abbr: "Wigan"},
	"Winchester Independents":                                      {abbr: "Winch"},
	"National Flood Prevention Party":                              {abbr: "NFPP"},
	"Old Windsor Residents Association":                            {abbr: "OWRA"},
	"the Borough first Independents":                               {abbr: "TBF"},
	"West Windsor Residents Association":                           {abbr: "WWRA"},
	"Independent Kidderminster Hospital and Health Concern":        {abbr: "IKHHC"},
	
	"Alliance - Alliance Party of Northern Ireland":                {abbr: "APNI"},
	"Aontú":                                                        {abbr: "Aontú"},
	"Democratic Unionist Party - D.U.P.":                           {abbr: "DUP"},
	"SDLP (Social Democratic & Labour Party)":                      {abbr: "SDLP"},
	"Sinn Féin":                                                    {abbr: "SF"},
	"Traditional Unionist Voice - TUV":                             {abbr: "TUV"},
	"Ulster Unionist Party":                                        {abbr: "UUP"},
	"People Before Profit Alliance":                                {abbr: "PBP"},
	
};
